### ISSUE TITLE
OCSP Stapling

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#18]
Hi,
i there also a plan to check for OCSP-Stapling on the mailserver Certificates?

**Comment by ivanr** [comment]
AFAIK, we currently check for OCSP stapling on all our TLS connections, but the information is not yet exposed in the UI. You confused me with the "also" part of your question, because we're not showing it for web servers yet either :) (We do show must-staple certificates, but we don't yet correlate with what the server is sending.) The answer is a "yes".

**Comment by Tributh** [comment]
Sorry,
when I have not clarified my question enough.
Will you check for the existence of the OID 1.3.6.1.5.5.7.1.24 inside of Mailserver certificates?
If it is an "OCSP Must-staple" certificate and show that in the UI later?
Beside this, it's good to know that the stapled OCSP signature will be verified as well.
With the "also" i just meant to add mailserver certificates in the UI with the OCSP Must-staple information.
I can see the OCSP-Must-Staple information actually only for the webservers.
Beside this I can't compare it any longer, since my mailserver felt into your "Sensitive SMTP domain" trap.
That happened on an massive delay ACL in my configuration.
The IPv4 of outbound.hardenize.com
is listed on zen.spamhaus.org
See:
 dig 232.98.75.147.zen.spamhaus.org +short
127.0.0.2
Look at: https://www.spamhaus.org/zen/
I have outbound.hardenize.com whitelisted now.

For an accurate check with your service you should get rid of this listing in this very widely used RBL List.

**Comment by ivanr** [comment]
Hmm, I would expect that we're already checking for must-staple on all certificates. Are you saying that you have one and we're not showing it? If so, please send me your hostname and I'll take a look.

Regarding Spamhaus, we're blacklisted because we're in the same (large) network block as someone else, and not because of anything we've done :( Our network provider claims that they're dealing with it. We'll monitor the situation and move elsewhere if we have to.

**Comment by ivanr** [comment]
FYI, I will remove your SMTP server from our blacklist.

**Comment by Tributh** [comment]
Send you the mailserver details in a separate mail. Thanx

**Comment by ivanr** [comment]
Thanks. I've removed your hosts from our blacklist, refreshed the results, and we're showing must-staple on the email certificates :)
