### ISSUE TITLE
External DMARC destinations not verified

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#26]
Hi,
you can put any email-address in your DMARC record.
If I would for example put
rua=mailto:ivan_privat@example.com in my mydomain.com
than Ivan gets a lot of unwanted DMARC reports later.
If such an example is put in an advisory sample, many peole will just copy it.
It could be of course also wanted or being legit.
For such a legitimate version you must allow on example.com to receive DMARC-report mails for mydomain.com
A TXT record must than be placed at
mydomain.com._report._dmarc.example.com

In this report
https://www.hardenize.com/report/yandex.com/1519662222#email_dmarc
you say "Policy is valid"
but their is no TXT record at
yandex.com._report._dmarc.yandex.ru 
for the rua addres.

https://tools.ietf.org/html/rfc7489#page-28
7.1.  Verifying External Destinations
6.  If the result includes no TXT resource records that pass basic
       parsing, a positive determination of the external reporting
       relationship cannot be made; stop.

If we assume the DMARC record could be valid, but the use of that given 
email address is NOT GRANTED

**Comment by ivanr** [comment]
I've made this better; there is now a check for all external destinations:
https://www.hardenize.com/report/yandex.com/1519896934#email_dmarc

Full disclosure: This was only a quick fix because our tests have not been finalised and there are edge cases that still don't work. In about 1-2 months we will start to go through all tests to fully implement them.

Thanks!
