### ISSUE TITLE
Calculating DNS lookups for SPF

### ISSUE THREAD

**Issue by tobbe-eklov** [hardenize/hardenize-public#28]
I have some issues with the DNS lookups for the mx label.
If we look at the domain sandviken.se hardenize says it's 10 ( today... )
It's true if we calculate the mx label to one. But in this case IMHO not correct.
If we read https://tools.ietf.org/html/rfc7208#section-4.6.4 it says 
"When evaluating the "mx" mechanism, the number of "MX" resource records queried is included in the overall limit of 10 mechanisms/modifiers that cause DNS lookups as described above."

So sandviken.se who has mail4.sandviken.se and mail5.sandviken.se, and they have both A and AAAA RR so IMHO I think sandviken.se should have 14, and not 10.
But harndenize are not alone, others also calculate the mx always to 1.

**Comment by ivanr** [comment]
I am not sure. That sentence says that the number of MX resource records in the policy is included should be counted toward the overall limit, which is why we're counting them as one. You're probably referring to the subsequent text:

```
In addition to that limit, the evaluation of each "MX" record MUST NOT result in
querying more than 10 address records -- either "A" or "AAAA" resource records.
If this limit is exceeded, the "mx" mechanism MUST produce a "permerror" result.
```

I understand this to mean that there are two limits when the mx term is used. One limit of 10 lookups for the SPF policy and then another (separate) limit of 10 lookups while evaluating the MX configuration.

**Comment by tobbe-eklov** [comment]
Yes, you are correct there.
But I think many is unaware of it. ( So was I .... :)
