### ISSUE TITLE
Hardeninze is not able to detect DANE?

### ISSUE THREAD

**Issue by wioxjk** [hardenize/hardenize-public#29]
Despite having deployed dane, and getting successful check with other tools like:
https://www.huque.com/bin/danecheck
https://dane.sys4.de/

Hardenize is unable to recognize it. Why?

The domain that the problem occurs on is selea.se

**Comment by ivanr** [comment]
I think this is an issue with the DNS cache. I refreshed the assessment and the port 443 DANE showed up. Although we're treating your SMTP servers as sensitive, running a test from our development environment shows DANE there too. IIRC, our DNS cache is currently at 1 hour, which is probably the culprit. Could you please confirm?

**Comment by wioxjk** [comment]
Hi,
I added TLSA for port 443, but I do also have it on port 25 on my MX and that does not show up.

I can only confirm that DANE under email still does not show up

**Comment by ivanr** [comment]
DANE not showing up is due to the fact that we're being blocked by some of the SMTP servers and are unable to fetch the certificates. We have #2 for that and it won't be long now before we make the next batch of improvements. I am closing this ticket as I don't think our DANE code is at fault. Thanks!

**Comment by wioxjk** [comment]
Even if the MX record for the other servers is removed - DANE and DNSSEC still does not show up.
Please check again and reopen the ticket.

**Comment by ivanr** [comment]
It's not showing up because we're caching SMTP assessments, see below:
![image](https://user-images.githubusercontent.com/485278/37454255-fc123fdc-2831-11e8-9348-d8d7331abe40.png)

However, after manually clearing the cache, DANE shows up as expected.

![image](https://user-images.githubusercontent.com/485278/37454541-c79998da-2832-11e8-812e-4aa1d9ce787b.png)

It's all green: https://www.hardenize.com/report/selea.se/1521105680#email

**Comment by wioxjk** [comment]
Alright!
I thought that pressing "Refresh report" would clean the cache.
Thanks for the help and guidance!
