### ISSUE TITLE
way to retest just a section

### ISSUE THREAD

**Issue by kooky** [hardenize/hardenize-public#3]
So if I'm changing settings on my mailservers, a way to do a retest just on the mailserver section.  

So that you can get a faster retest.

**Comment by ivanr** [comment]
Hi @kooky and thanks for your feature request!

My thinking is that there should be a "workbench" section at some point where individual tests can be run, for everything that Hardenize does. The workflow would be: 1) full assessments run continuously, then 2) when you're changing something you go to the workbench where you can quickly iterate.

This is not something that will happen in the short-term, as there is a lot of other work to do first. For that reason I am going to temporarily close this ticket, but I am marking it as "iced" so that it's not forgotten.
