### ISSUE TITLE
#www_tls has probably a problem with multiple CNAME records?

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#4]
#www_https has a result, #www_tls not.
https://www.hardenize.com/report/dataservices.spd.de/1506361225#domain_dns
* My "dig" only returns one CNAME record, Hardenize sees multiple ones.
* www.spd.de is a CNAME, but it works: https://www.hardenize.com/report/spd.de#www_tls

---
Please edit the title. I can't find a proper description.

**Comment by ivanr** [comment]
No, Hardenize saw too many redirections while following HTTPS redirections and then got confused and ignored that endpoint. As a short-term fix I increased how many redirections we allow (from 5 to 15). We're now inspecting TLS on this host. The confusion should be cleared when this part of code is rewritten, which is planned.

We show too many CNAMEs. I haven't looked at that yet, but I will leave this issue open until I do. It's probably because we just show all DNS lookups we do during the assessment.

**Comment by ivanr** [comment]
The CNAME problem has been fixed recently: https://www.hardenize.com/report/dataservices.spd.de/1511946561#domain_dns
